[package]
name = "bevy-world-space"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", default-features = false, features = ["bevy_core_pipeline", "bevy_window"] }
ordered-float = "5.0.0"
